### ISSUE TITLE
TypeError: core_1.utils.tryToMutePuppeteerWarning is not a function

### ISSUE THREAD

**Issue by jeswr** [facebook/memlab#97]
In trying to upgrade from `@memlab/api` 1.0.23 -> 1.0.24 the following error message occurs in [the CI of the eye-js project I maintain](https://github.com/eyereasoner/eye-js/pull/540).

```
TypeError: core_1.utils.tryToMutePuppeteerWarning is not a function
    at Object.<anonymous> (/home/runner/work/eye-js/eye-js/node_modules/@memlab/api/dist/lib/APIUtils.js:32:22)
    at Generator.next (<anonymous>)
    at /home/runner/work/eye-js/eye-js/node_modules/@memlab/api/dist/lib/APIUtils.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/eye-js/eye-js/node_modules/@memlab/api/dist/lib/APIUtils.js:13:12)
    at Object.getBrowser (/home/runner/work/eye-js/eye-js/node_modules/@memlab/api/dist/lib/APIUtils.js:29:12)
    at /home/runner/work/eye-js/eye-js/node_modules/@memlab/api/dist/API.js:236:54
    at Generator.next (<anonymous>)
    at /home/runner/work/eye-js/eye-js/node_modules/@memlab/api/dist/API.js:17:71
    at new Promise (<anonymous>)
```

This occurs when [this](https://github.com/eyereasoner/eye-js/blob/main/__tests_memory__/browserLeakTest.js) script is run as triggered by [this command](https://github.com/eyereasoner/eye-js/blob/1ab63b5c13e898200c9e14dbb7776a574a009e28/package.json#L20).

**Comment by JacksonGL** [comment]
@jeswr `@memlab/api` 1.0.24 is using a newer version of `@memlab/core` which includes a new API (`tryToMutePuppeteerWarning`). Please consider upgrading all `@memlab/*` packages to the latest version.

**Comment by jeswr** [comment]
Indeed just npm upgrading everything seems to work. Thanks @JacksonGL !
